version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yc0125
    ports:
      - "3306:3306"
    volumes:
      - ./initsql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  web:
    build: .
    command: python app.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork: